name: Caching Primes
on: workflow_dispatch
jobs:
  save:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          cache
          !cache/unwanted/2/3
        key: ${{ github.workflow }}/${{ github.run_number }}-${{ github.run_attempt }}
    - run: |
        mkdir -p cache/wanted cache/unwanted
        > cache/wanted/example.txt
        > cache/unwanted/example.txt
  restore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          cache
          !cache/unwanted/2/3
        key: ${{ github.workflow }}/${{ github.run_number }}-${{ github.run_attempt }}
    - run: |
        find cache > "$GITHUB_STEP_SUMMARY"
