jobs:
  save:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          cache
          !cache/unwanted
        key: ${{ github.workflow }}/${{ github.run_number }}-${{ github.run_attempt }}
    - run: |
        mkdir -p cache/wanted cache/unwanted
        > cache/wanted/example.txt
        > cache/unwanted/example.txt
  restore:
    needs: [save]
    runs-on: ubuntu-latest
    steps:
    - run: sleep 15 # save is somehow delayed???
    - uses: actions/cache@v3
      with:
        fail-on-cache-miss: true
        path: cache
        key: ${{ github.workflow }}/${{ github.run_number }}-${{ github.run_attempt }}
    - run: find cache > "$GITHUB_STEP_SUMMARY"
on: workflow_dispatch
name: Example
